### ISSUE TITLE
Makefile: Linking?

### ISSUE THREAD

**Issue by sjaehn** [brummer10/libxputty#10]
Hi Hermann,

me again. I also took a short view to the build process. And I found this: https://github.com/brummer10/libxputty/blob/10aac63b6d3fde177ef0cf07d014c3bff3d72688/Build/Makefile#L147-L148

On the one hand, you suppress linking using the `-c` flag. And on the other hand you pass the `LDFLAGS`. Is it a bug or does it make sense? Please apologize my question, but I'm still having a real struggle with linking at all.

Viele Grüße
Sven

**Comment by brummer10** [comment]
Hi
Yes, the LDFLAGS wasn't needed here, just they didn't harm so I leave them there.

**Comment by sjaehn** [comment]
OK, thanks for info.
