### ISSUE TITLE
What is wrong?

### ISSUE THREAD

**Issue by ficorax** [brummer10/libxputty#14]
Hi.
I am trying you libxputty library. Looks promising!
But I have some problems. When I compile [simple-example](https://brummer10.github.io/libxputty-docs/docs/html/simple-example_8c-example.html) then I get something like that:
![Screenshot from 2024-12-21 20-48-52](https://github.com/user-attachments/assets/98b73d98-5410-450c-9d76-46806bf2ff85)

After resizing window I have:

![Screenshot from 2024-12-21 20-50-06](https://github.com/user-attachments/assets/1e971df5-b846-42dd-bdf5-119926198950)

But when I compile XGain.lv2 plugin example the in Ardour everything looks fine.
Do you have the same issue?

**Comment by brummer10** [comment]
Nice to hear you like it.
No, it redraw here as it should.
It looks like the expose events get filtered out . I've implemented a filter to reduce redrawing to the minimum.
You could try to set the FAST_REDRAW flag for the window to disable this filter.

`w->flags |= FAST_REDRAW;`

if that doesn't work, you could connect the `configure_notify_callback` or the `resize_notify_callback` to the `draw_window`
function.

`w->func.configure_notify_callback = draw_window;`
`w->func.resize_notify_callback = draw_window;`

**Comment by ficorax** [comment]
Hi again.
I was checking every possibilities that you mentioned. Seems like no one is working. It is strange, in Ardour XGain behave correct but in another (Carla, Zrythm) XGain is acting like above example.

**Comment by brummer10** [comment]
Do you use wayland?

**Comment by ficorax** [comment]
Yes...
Are you kidding? :D

**Comment by ficorax** [comment]
Problem solved...
Thanks a lot!
