### ISSUE TITLE
Build breaks: error: target emulation unknown: -m or at least one .o file required

### ISSUE THREAD

**Issue by yurivict** [brummer10/libxputty#6]
```
cd ../xputty/resources/ && ld -r -b binary approved.png -o ../../Build/approved.o
ld: error: target emulation unknown: -m or at least one .o file required
gmake[3]: *** [Makefile:81: approved.o] Error 1
```

**Comment by brummer10** [comment]
https://github.com/brummer10/GxPlugins.lv2/issues/9#issuecomment-431634711

Still I've no idea how to implement it so that it would work with both linkers

**Comment by brummer10** [comment]
So, here you go.
I've implement a check now if ld.lld from LLVM is involved, and if so, set the needed flags to make it work. 
Unfortunately lld requires to define the target architecture, were I don't now all the needed flags to fetch them, so I only check for  x86_64 / i386. 
If you need support for more targets, I'm open for patches/pull requests as usual.

regards
hermann

**Comment by yurivict** [comment]
But now it fails like this on amd64:
```
cd ../xputty/resources/ && ld -r -b binary -m  -z noexecstack approved.png -o ../../Build/approved.o
ld: error: unknown emulation: -z
ld: error: cannot open noexecstack: No such file or directory
```

**Comment by brummer10** [comment]
which version of lld do you use?
I use LLD 11.0.1

**Comment by yurivict** [comment]
It's 10.0.1 - matching base clang installation of version 10.0.1.

**Comment by brummer10** [comment]
what is your output of `uname -a`

**Comment by yurivict** [comment]
```
$ uname -a
FreeBSD xx.xx.xx 12.2-STABLE FreeBSD 12.2-STABLE #0 r369260M: Fri Feb 12 21:13:14 PST 2021     unknown@nohost.com:/disk/sys/usr/src/amd64.amd64/sys/GENERIC  amd64
```

**Comment by brummer10** [comment]
Thanks, so here is a other try to solve it. Please update and try, and let me know if it fix the issue for you.

regards
hermann

**Comment by yurivict** [comment]
Now this failure is gone.
Thanks!

**Comment by Iey4iej3** [comment]
> I've implement a check now if ld.lld from LLVM is involved, and if so, set the needed flags to make it work.
> Unfortunately lld requires to define the target architecture, were I don't now all the needed flags to fetch them, so I only check for x86_64 / i386.

It might be better to use configuration systems such as [CMake](https://cmake.org/) to "control the software compilation process using simple platform and compiler independent configuration files, and generate native makefiles and workspaces that can be used in the compiler environment of your choice." It would do all the jobs for you automatically.

**Comment by Praveenganisetti** [comment]
> Now this failure is gone. Thanks!

What's the solution ?
